### ISSUE TITLE
Missing call to add BasiGX repository in installation documentation

### ISSUE THREAD

**Issue by chrismayer** [terrestris/shogun2-client#10]
I just tried to install SHOGun2-client as it is described [here](https://github.com/terrestris/shogun2-client#installation). Before running 
``sencha app upgrade /path/to/extjs`` 
I had to call 
``sencha package repo add BasiGX http://terrestris.github.io/BasiGX/cmd/pkgs``. 

Otherwise I got an error `` Failed to resolve package BasiGX``. Is this missing in the documentation or did I miss something?

**Comment by marcjansen** [comment]
Definitely missing. PR welcome as always.
