### ISSUE TITLE
Open a default application after installation

### ISSUE THREAD

**Issue by chrismayer** [terrestris/shogun2-client#11]
Is there a default application which can be opened after the installation of SHOGun2-Client? I tried to open something like ``http://localhost:8080/shogun2-webapp-test/client/?id=4711`` but I just got a HTTP 403 errors even although I did a successful login as admin before.

![shogun2](https://cloud.githubusercontent.com/assets/1185547/11625530/f2f0d6b8-9cdb-11e5-83ee-ae0e0e491200.png)

Thanks for any hint.

**Comment by marcjansen** [comment]
We'll look into this @chrismayer. Probably also related to recent changes. Thanks a lot for trying it! We'll report back here. If you can find out the root of the issue yourself, just tell us.

**Comment by dnlkoch** [comment]
Please try the following:

1. Adapt and open this URL:

   `http://localhost:8080/{{YOUR_SHOGUN2_WEBAPP_NAME}}/application/findAll.action`

2. The response will list all of your current SHOGun2 applications (and normally it should return the default one named _Default Application_ only).

3. Find the entry `id` containing the ID of the application (e.g. `"id": 50`). 

4. Use this ID as GET parameter like:

   `http://localhost:8080/{{YOUR_SHOGUN2_WEBAPP_NAME}}/client/index.html?id=50`

I admit that this workflow isn't very neat at the moment (...), but please let me know if it works for you!

**Comment by chrismayer** [comment]
Thanks @dnlkoch for your help. The workflow described by you allowed me to open the ``Default Application``.

**Comment by dnlkoch** [comment]
Good!

**Comment by chrismayer** [comment]
Maybe this should also go to the installation section of the README, what do you think @dnlkoch? Although it is not "neat " it allows possible user to check if everything works in a correct way.

**Comment by dnlkoch** [comment]
Absolutely! Thanks for your support @chrismayer!

**Comment by chrismayer** [comment]
I am reactivating this issue since the default application does not load anymore after upgrading the SHOGun2 to the current master (0.0.3-SNAPSHOT):

On startup of the client the call to ``http://localhost:8080/{{my-web-app}}/application/get.action?id={{my-id}}`` results in a HTTP 404. So there is no application context and the application cannot load. Is this web interface gone or is it a fault of mine? Since there seems to be a REST controller now I also tried to call ``http://localhost:8080/{{my-web-app}}/applications/{{my-id}}/`` but this also ends in a HTTP 404. 

Thanks for any hint.

**Comment by buehner** [comment]
Hi @chrismayer ,

i think the first interface (`get.action`) has been removed during a cleanup. (There is only a `findAll.action` remaining) But the REST interface should work. I could succesfully try it. I think you just forgot the `/rest/` in the URL:

`http://localhost:8080/{{my-web-app}}/rest/applications/{{my-id}}/`

Hope this helps

**Comment by chrismayer** [comment]
Hi @buehner,

correct I didn't notice that there has to be a ``/rest/`` in the URL. The URL you provided works, thank you!
Nevertheless the URL used in the client has been incorrect as well. I opened a PR #15 to correct this.
